apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    #repoURL: oci://quay.io/jetstack/charts/cert-manager
    repoURL: quay.io/jetstack/charts/cert-manager
    targetRevision: v1.18.2
    helm:
      releaseName: cert-manager
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
